spring:
  profiles:
    active: local
    group:
      local: common,secret
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: templates/
      suffix: .html

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    path: /error
    whitelabel:
      enabled: true